# Generated by Django 3.1.4 on 2020-12-15 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_orders_user'),
        ('user', '0002_delete_jwt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_orders', to='products.orders'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_image', to='products.genericfileupload'),
        ),
    ]
